### ISSUE TITLE
Alignment issues with InsertInstructionPatch

### ISSUE THREAD

**Issue by calebh** [purseclab/Patcherex2#27]
As I've been writing some test cases for `InsertInstructionPatch` when `language="C"`, I've come across segmentation faults that occur when data sections are not aligned properly. As an example, take a look at the following program in Ghidra:

![image](https://github.com/purseclab/Patcherex2/assets/53128179/79c900f1-7549-4ba5-b159-6d439e6389cf)

The highlighted instruction is accessing a chunk of readable data, and the argument needs to be 16 byte aligned. Running this program results in a segfault due to misalignment. Other instructions in this micropatch seem to have a similar problem.

Here is the error in gef:

![image](https://github.com/purseclab/Patcherex2/assets/53128179/5b85ce24-7887-4a24-b844-511d00729186)

There seems to be a chicken and egg problem with the patch, where you don't know the true size of the patch until you know its insertion address, but to get the address of the patch you need the size. Right now I believe we first get the size by assuming the compiled function starts at address 0. Could this be related to the alignment bug?

Although this problem cropped up with the `InsertIntructionPatch`, I assume this issue also crops up in `InsertFunctionPatch`.

I have attached the binaries (before and after patch) and the Python script needed to reproduce the issue (you need to run the Python script on the [draperlaboratory fork](https://github.com/draperlaboratory/Patcherex2/)). I have also attached the log of running the Python script, which prints out what the `MICROPATCH` function is:

[iip_c_alignment_bug.zip](https://github.com/purseclab/Patcherex2/files/14983784/iip_c_alignment_bug.zip)

**Comment by DennyDai** [comment]
Thank you for providing the binaries that demonstrated the issue! I've fixed it in commit https://github.com/purseclab/Patcherex2/commit/6bc4e580fe7b085dd35d464455d88a62a334e0a8.Now the alignment should be handled properly. You will just need to apply the same change in the Draper fork.

Please let me know if you have any questions regarding this.

**Comment by calebh** [comment]
Great! This fixed the alignment issue - the problem went away as soon as I merged in your change without any further work.

There does still seem to be size differences depending on what you set the `base` relocation address to. I will open a separate issue for that after I spend some time further analyzing the problem.
