### ISSUE TITLE
.eh_frame (exception frame) section getting tacked onto compiled C code for some bases

### ISSUE THREAD

**Issue by calebh** [purseclab/Patcherex2#29]
When working on the InsertInstructionPatch lang="C" code, I ran across some scenarios where the `.eh_frame` section was getting tacked onto the output from `Compiler.compile`. Here is what was causing the error for me:

- When `base=0` was passed to `Compiler.compile`, the `.eh_frame` section was not directly adjacent to the `.text` section, so `Compiler.comple` did not return that section.
- When `base=0x5edb` was passed to `Compiler.compile`, the `.eh_frame` was placed directly adjacent to the `.text` section, and was returned by `Compiler.compile`.
- This caused a size discrepancy error, where there wasn't enough allocated space for the version compiled with the correct offset. However since the content of `.eh_frame` is completely useless for us, it can be safely omitted.
- I solved the issue by adding an extra compiler flag `-fno-asynchronous-unwind-tables` to stop the section from being outputted from the compiler in the first place.
- I'm not sure if this is the ideal fix, maybe it would be possible for other sections to be accidentally returned by `Compiler.compile`.

I fixed this issue by passing the compiler flag `-fno-asynchronous-unwind-tables` here:

1. https://github.com/draperlaboratory/Patcherex2/blob/main/src/patcherex2/components/utils/utils.py#L79
2. https://github.com/draperlaboratory/Patcherex2/blob/main/src/patcherex2/components/utils/utils.py#L137

I have attached the files in the compiler `/tmp` directory for both the version where `-fno-asynchronous-unwind-tables` was passed, and the version where it wasn't.

[eh_frame_bug.zip](https://github.com/purseclab/Patcherex2/files/15098124/eh_frame_bug.zip)

We may want to add `-fno-asynchronous-unwind-tables` as a default flag to pass to the compiler, or fix the section extraction code.

Here are two screenshots from Ghidra showing the adjacency of the text section:

At base 0:
![image](https://github.com/purseclab/Patcherex2/assets/53128179/2dcc0772-2bde-4b04-a6af-b2a8c62a4258)

At base 0x5edb (notice that `.eh_frame` is now directly adjacent):
![image](https://github.com/purseclab/Patcherex2/assets/53128179/edabba69-6e1f-425b-8ad4-7cb6f8614ad7)

**Comment by DennyDai** [comment]
Thank you for providing the details. I recall encountering a similar issue previously, but was in a rush so I just left a TODO comments in the code and totally forgot about it. It should be now fixed, and it should no longer return any adjacent sections.
