### ISSUE TITLE
Make pyhidra dependency optional

### ISSUE THREAD

**Issue by twizmwazin** [purseclab/Patcherex2#34]
I tried pip installing the latest version of patcherex2 from github and it failed due to JPype not providing a wheel for my platform (aarch64 linux) and me not having a JVM installed that it could build with. Unless this functionality is core to patcherex2, can it be made optional? Thanks!

**Comment by DennyDai** [comment]
I've just made it optional. The change has been pushed to PyPI as well :)

**Comment by twizmwazin** [comment]
Thank you!
